apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-simulator-scripts
data:
  test-script.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export default function () {
      const res = http.get('http://httpbin.org/status/200,500,404');
      sleep(1);
    }
