apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-simulator-scripts
  namespace: default
data:
  test-script.js: |
    import http from 'k6/http';
    import { check } from 'k6';

    export default function () {
      const res = http.get('http://test-server.local');
      check(res, {
        'status is 200': (r) => r.status === 200,
      });
    }
