apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-simulator
  labels:
    app: traffic-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-simulator
  template:
    metadata:
      labels:
        app: traffic-simulator
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: scripts
        configMap:
          name: traffic-simulator-scripts
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
      - name: prometheus-data
        emptyDir: {}
      - name: grafana-storage
        emptyDir: {}
